version: "3.9"

services:
  db:
    image: postgres:15-alpine
    volumes:
      - dev-db-data:/var/lib/postgresql/data
    container_name: go_gin_job_search_db
    environment:
      - POSTGRES_DB=go_gin_job_search_db
      - POSTGRES_USER=devuser
      - POSTGRES_PASSWORD=admin
    ports:
      - "5432:5432"

  elasticsearch:
    container_name: go_gin_job_search_es
    image: elasticsearch:7.17.9
    environment:
      - bootstrap.memory_lock=true
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
      - cluster.name=job-search-esearch
      - discovery.type=single-node
      - node.name=job-search-es-node
    ulimits:
      memlock:
        hard: -1
        soft: -1
    ports:
      - "9200:9200"
    networks:
      - es-job-search
    healthcheck:
      interval: 10s
      retries: 20
      test: curl -s http://localhost:9200/_cluster/health | grep -vq '"status":"red"'
    depends_on:
      - db

  kibana:
    image: kibana:7.17.10
    container_name: go_gin_job_search_kibana
    depends_on:
      elasticsearch:
        condition: service_healthy
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
    networks:
      - es-job-search
    healthcheck:
      interval: 10s
      retries: 20
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5601/api/status

networks:
  es-job-search:
    driver: bridge

volumes:
  dev-db-data: